# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CfC-t38-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CfC-t38-iOS
  pod 'QRCodeReader.swift', '~> 10.1.0'

  target 'CfC-t38-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CfC-t38-iOSUITests' do
    # Pods for testing
  end

end
